export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST';
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS';
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL';

export const REVIEW_STATUS_REQUEST = 'REVIEW_STATUS_REQUEST';
export const REVIEW_STATUS_SUCCESS = 'REVIEW_STATUS_SUCCESS';
export const REVIEW_STATUS_FAIL = 'REVIEW_STATUS_FAIL';

export const ADMIN_REVIEWS_REQUEST = 'ADMIN_REVIEWS_REQUEST';
export const ADMIN_REVIEWS_SUCCESS = 'ADMIN_REVIEWS_SUCCESS';
export const ADMIN_REVIEWS_FAIL = 'ADMIN_REVIEWS_FAIL';

export const MY_REVIEWS_REQUEST = 'MY_REVIEWS_REQUEST';
export const MY_REVIEWS_SUCCESS = 'MY_REVIEWS_SUCCESS';
export const MY_REVIEWS_FAIL = 'MY_REVIEWS_FAIL';
